package com.smartbear.time;/*
 * This source file was generated by the Gradle 'init' task
 */

import com.smartbear.time.exceptions.InvalidTimeException;
import com.smartbear.time.models.NumericTime;
import com.smartbear.time.service.dialects.british.BritishSpokenTimeService;
import com.smartbear.time.service.io.UserInput;

public class App {
    private String getSpokenTime() throws InvalidTimeException {
        UserInput input = UserInput.getInstance();
        NumericTime numericTime = input.getNumericTime();
        BritishSpokenTimeService bt = new BritishSpokenTimeService();
        bt.getSpokenTime(numericTime);
    }

    public static void main(String[] args) {
        System.out.println(new App().getBritishTime());
    }
}
