package com.smartbear.time;/*
 * This source file was generated by the Gradle 'init' task
 */

import com.smartbear.time.exceptions.InvalidTimeException;
import com.smartbear.time.models.NumericTime;
import com.smartbear.time.service.ISpokenTimeService;
import com.smartbear.time.service.dialects.british.BritishSpokenTimeService;
import com.smartbear.time.service.io.UserInput;

public class App {
    private void getSpokenTime(ISpokenTimeService spokenTimeService) throws InvalidTimeException {
        UserInput input = UserInput.getInstance();
        NumericTime numericTime = input.getNumericTime();
        System.out.println("Spoken time : " + spokenTimeService.getSpokenTime(numericTime));
    }

    public static void main(String[] args) throws InvalidTimeException{
        BritishSpokenTimeService bt = new BritishSpokenTimeService();
        new App().getSpokenTime(bt);
    }
}
